project:
  type: website
  output-dir: docs
execute:
  echo: false
  output: true
  cache: true
  freeze: true
  embed-resources: true

# Remove the metadata-files line
resources:
  - "*.ipynb"

website:
  title: "My Portfolio"
  site-url: "https://github.com/AmeNach/my-porfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        menu:
          - text: "Fastai"
            href: posts/fastai/index.qmd
          - text: "Kaggle Competitions"
            href: posts/kaggle/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/AmeNach/my-porfolio
  page-footer:
    left: "© 2025 Amel Nait Achour"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: flatly
    toc: true
    code-fold: false
    html-math-method: katex